-- MySQL Script generated by MySQL Workbench
-- Fri Nov 24 16:43:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nivel_de_agua_e_luminosidade
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nivel_de_agua_e_luminosidade` ;

-- -----------------------------------------------------
-- Schema nivel_de_agua_e_luminosidade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nivel_de_agua_e_luminosidade` DEFAULT CHARACTER SET utf8 ;
USE `nivel_de_agua_e_luminosidade` ;

-- -----------------------------------------------------
-- Table `nivel_de_agua_e_luminosidade`.`planta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nivel_de_agua_e_luminosidade`.`planta` ;

CREATE TABLE IF NOT EXISTS `nivel_de_agua_e_luminosidade`.`planta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM("boa noite", "comigo ninguem pode") NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nivel_de_agua_e_luminosidade`.`umidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nivel_de_agua_e_luminosidade`.`umidade` ;

CREATE TABLE IF NOT EXISTS `nivel_de_agua_e_luminosidade`.`umidade` (
  `valor` INT NULL,
  `planta_id` INT NOT NULL,
  `instante` DATETIME NULL,
  UNIQUE INDEX `instante_UNIQUE` (`instante` ASC),
  CONSTRAINT `fk_umidade_plantas`
    FOREIGN KEY (`planta_id`)
    REFERENCES `nivel_de_agua_e_luminosidade`.`planta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nivel_de_agua_e_luminosidade`.`luminosidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nivel_de_agua_e_luminosidade`.`luminosidade` ;

CREATE TABLE IF NOT EXISTS `nivel_de_agua_e_luminosidade`.`luminosidade` (
  `valor` INT NULL,
  `planta_id` INT NOT NULL,
  `instante` DATETIME NULL,
  UNIQUE INDEX `instante_UNIQUE` (`instante` ASC),
  CONSTRAINT `fk_luminosidade_plantas1`
    FOREIGN KEY (`planta_id`)
    REFERENCES `nivel_de_agua_e_luminosidade`.`planta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nivel_de_agua_e_luminosidade`.`quantidade_de_agua`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nivel_de_agua_e_luminosidade`.`quantidade_de_agua` ;

CREATE TABLE IF NOT EXISTS `nivel_de_agua_e_luminosidade`.`quantidade_de_agua` (
  `valor` INT NULL,
  `planta_id` INT NOT NULL,
  `instante` DATETIME NULL,
  UNIQUE INDEX `instante_UNIQUE` (`instante` ASC),
  CONSTRAINT `fk_quantidade_de_agua_plantas1`
    FOREIGN KEY (`planta_id`)
    REFERENCES `nivel_de_agua_e_luminosidade`.`planta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
